### ISSUE TITLE
Support closeOnOutsideClick for nested menus

### ISSUE THREAD

**Issue by mtmacdonald** [everweij/react-laag#29] opened 2020-01-22 08:42 UTC
Is it possible to make the `closeOnOutsideClick` setting work for nested popovers/menus?

I.e. if I have a nested menu, it should close when I click outside all of the menu layers, but not close the entire menu if I click inside a child layer (as it currently does).

If not, is there any workaround I can use?

<img width="344" alt="Screenshot 2020-01-22 at 09 40 50" src="https://user-images.githubusercontent.com/2428859/72878498-57758980-3cfb-11ea-8672-cd1842868623.png">

**Comment by everweij** [comment] 2020-01-23 20:01
I agree this is something that needs to be fixed!
Need sure how though, need to think about this for a moment 🤔

**Comment by everweij** [comment] 2020-02-09 21:45
@mtmacdonald ,
I've added detection for nested layers inside the 'closeOnOutsideClick'-handling. By upgrading to v0.7.1 your issue should be fixed. Please, let me know if this works for you.

**Comment by mtmacdonald** [comment] 2020-02-10 16:25
@everweij thanks a lot, that made a big a difference. It also resolved my related issue where sibling submenus could incorrectly be opened simulataneously, like so:

<img width="329" alt="Screenshot 2020-02-10 at 17 18 15" src="https://user-images.githubusercontent.com/2428859/74168077-7d6eb980-4c29-11ea-86fd-7c0b102ede57.png">

I now wonder if `onOutsideClick()` could be similarly updated (or should that be a separate ticket)? When I tried a different approach of managing and setting `isOpen` myself, I tried to use `onOutsideClick()`, but it fires separately for each layer (i.e. it still fires for the other layers if I click inside one layer). Would it be possible to have something `onOutsideAllClick()` which fires only if you click outside all layers?

**Comment by mtmacdonald** [comment] 2020-02-10 18:04
It seems that when `closeOnOutsideClick` is `true`, `toggleLayerProps.isOpen` is now always false? Which means that I can no longer close the menu by clicking on the trigger (only by clicking outside the menu).

**Comment by mtmacdonald** [comment] 2020-02-10 18:32
Could we have a `closeAll()` handler? I'm calling `close` (e.g. upon clicking on an option) but I'm finding that it doesn't close all layers.

<img width="344" alt="Screenshot 2020-02-10 at 19 29 30" src="https://user-images.githubusercontent.com/2428859/74178409-d8111100-4c3b-11ea-85f1-5badf8bef74d.png">

<img width="366" alt="Screenshot 2020-02-10 at 19 29 36" src="https://user-images.githubusercontent.com/2428859/74178423-de06f200-4c3b-11ea-8f64-f2c6a87a22c7.png">

**Comment by mtmacdonald** [comment] 2020-02-10 19:28
I've attached a minimum example of my remaining `useToggleLayer` issues:

- `toggleLayerProps.isOpen` isn't working when `closeOnOutsideClick` is true (so I can't close the top-level menu by clicking on the trigger button. To reproduce try clicking the 'Menu' button to close the menu)
- `close` doesn't allow me to close the entire menu when clicking an option (it closes some layers but not the root layer. To reproduce try clicking 'Area Charts')

`npm install` and `npm run storybook` to run, then see the 'with sub-menus story'.

[menu.zip](https://github.com/everweij/react-laag/files/4182660/menu.zip)

**Comment by everweij** [comment] 2020-02-10 19:45
Thanks @mtmacdonald  for looking into this, very helpful 👍🏼
I will try some things out tomorrow. Will let you know where I will come up with.

**Comment by everweij** [comment] 2020-02-11 20:58
Hi @mtmacdonald ,

I looked into the issues you were experiencing. Here are my findings:

> `toggleLayerProps.isOpen` isn't working when `closeOnOutsideClick` is true (so I can't close the top-level menu by clicking on the trigger button. To reproduce try clicking the 'Menu' button to close the menu)

I found the cause of this bug, this should now be fixed in 1.7.2.

> `close` doesn't allow me to close the entire menu when clicking an option (it closes some layers but not the root layer. To reproduce try clicking 'Area Chart')

I forgot to mention last weekend that by nesting multiple layers, the nested layers 'pass control' of the outside-clicking-behavior to the first layer in the tree that has `closeOnOutsideClick=true`. In most menu scenario's you have a root menu (with `closeOnOutsideClick=true`), and optional various sub-menu's (with `closeOnOutsideClick=false`).

As far as closing the entire menu from within a submenu is concerned: You could pass the `close()` of the root menu-layer down to the submenu's. So by closing the root menu, all other sub-menu's will unmount automatically as well.

I've updated your zip-file with a few lines of code. You can find them by searching for comments that start with 'Erik'

Let me know if this works for you :)
[menu (1.7.2).zip](https://github.com/everweij/react-laag/files/4188279/menu.1.7.2.zip)

**Comment by everweij** [comment] 2020-02-11 21:02
Oh , by the way, I should probably document the nested closeOnOutsideClick stuff more thoroughly 😅

**Comment by mtmacdonald** [comment] 2020-02-11 21:17
Thank you very much! I will check tomorrow and get back to you. Really appreciate the help.

**Comment by mtmacdonald** [comment] 2020-02-12 17:16
I've had time to look at this in detail now and to get it working in a form I'm happy with. The main challenge I still had was preventing sibling nested menus from being open simultaneously. I managed to handle it by tracking all the close handlers of relevant layers so I could close sibling layers before opening a new submenu. Works but seemed like a lot of effort! Perhaps there's a better way, or it could be somehows included in react-laag in future.

I also stopped some event propagation so that for example, clicking on a heading in the layer wouldn't close the menu. 

Apart from those points, your fixes solved my issues. Thanks again for all the help. I'm attaching the working solution in case its helpful for your future improvements, or inspiration for your examples/docs.

[menu-working.zip](https://github.com/everweij/react-laag/files/4193756/menu-working.zip)

**Comment by everweij** [comment] 2020-02-13 12:34
Hi @mtmacdonald,
Good to hear you managed to get it to work!

I agree it's a tricky area to solve -> managing layers in a group setting. I think that in the future there should be some kind of mechanism which handles open / close behavior of these kind of related toggle-layers (like nested menu's). Right now, I think I rather put this logic inside an own hook or component, because I want to limit the complexity and responsibilities that ToggleLayer / useToggleLayer currently has.

Thanks for sharing your code, helpful stuff 👍🏼

**Closed** 2020-02-23 21:04 UTC
