### ISSUE TITLE
[BUG] Animating useLayer doesn't work on first trigger [framer-motion@4.1.13] 

### ISSUE THREAD

**Issue by linden-dg** [everweij/react-laag#69] opened 2021-05-10 10:49 UTC
**Describe the bug**
The first time a Layer (produced by `useLayer`) is toggled/triggered open, it doesn't correctly transition from the framer-motion `initial` state to the `animate` state (it gets stuck in `initial`).

It looks like this issue is unique to `framer-motion@4.1.13`, and could be related to [this commit](https://github.com/framer/motion/commit/fb7f0ca361723ad8a647a37832fadc0655a1745b)

**To Reproduce**
1. Go to https://codesandbox.io/s/animation-initial-issue-3jbzb?file=/src/index.js 
         - (adapted from example https://github.com/everweij/react-laag#animations)
2. Click on 'Trigger React Laag Layer' button
3. In the console you can see that `isOpen` is being toggled `true`/`false`
4. But the first `isOpen` doesn't properly animate between the `initial` and `animate` state
5. Only when `isOpen` has been toggled to `false`, **then back to `true`** does the animation work (i.e. 3 clicks needed)
6. The second button shows that regular framer animations still work just fine on first click

**Expected behavior**
Clicking on the trigger element should open Layer on first go, not require 3 clicks

**Browser / OS (please complete the following information):**
 - OS: Windows
 - Browser: tested on Chrome v90.0 and Firefox v89.0

**Additional context**
Given the regular framer example works, I assume this is a laag/framer-motion interaction. But if it's better to post this on framer-motion, then let me know

**Comment by everweij** [comment] 2022-04-12 11:47
I just forked your codesandbox and updated the deps to react-laag@2.0.4 / framer-motion@6.2.9 and it seems like the issue is fixed by now.

**Closed by everweij** 2022-04-12 11:47 UTC
Labels: bug
